In [4]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np
import tensorflow as tf

In [85]:
class Optimizer():
    def __init__(self):
        self.sess = tf.Session()
        init_op = tf.initialize_all_variables()
        self.sess.run(init_op);
        
        self.variables = tf.global_variables()
        self.generateInitialPoblation()
        
    def printData(self):
        iterator = self.data.make_initializable_iterator()
        self.sess.run(iterator.initializer)
        next_element = iterator.get_next()
        item =  next_element
        while True:
            try: 
                item =self.sess.run(next_element)
                print(item)
            except tf.errors.OutOfRangeError:
                break
        
    def setFunction(self,model):
        self.model = model 
    
    def evaluationSurvival(self,function = None , poblation = None ):
        poblation = self.data
        function = self.evaluationTensor
        def temporal(*x):
            return {"people":x,"survive":self.evaluationTensor(x)}
        return poblation.map(temporal)
    
    def evaluationTensor(self,x):
        i= 1
        for variable in x:
            print(self.sess.run(self.variables[i]))
            print(variable)
            self.sess.run(self.variables[i].assign(tf.Variable(variable) ) )
            i +=1
        return self.sess.run(self.function)
            

    def generateInitialPoblation(self,cant = 30):
        rows = []
        for variable in self.variables:
            col = []
            for i in range(cant):
                col.append( tf.random.uniform(variable.shape))
            rows.append(col)
        self.data = tf.data.Dataset.from_tensor_slices(tuple(rows))
    
    def interation(self,dataset = None):
        dataset = self.data
        dataset = self.evaluationSurvival(poblation=dataset)
        iterator = dataset.make_initializable_iterator()
        sess.run(iterator.initializer)
        next_element = iterator.get_next()
        item =  next_element
        while True:
            try: 
                compare= tf.less(item["survive"],sess.run(next_element)["survive"])
                if sess.run(compare):
                    item =sess.run(next_element)
                    print(item)
            except tf.errors.OutOfRangeError:
                break
        this.data = self.fixFunction()
    
    def fixFunction(self):
        def temporal(*x):
            newpeople = item["people"] + x["people"] / 2 #put some function
            return {"people":newpeople,"survive":evaluationSurvival(newpeople)}
        return poblation.map(temporal)

    

In [9]:
features, labels = (np.random.sample((100,1)), np.random.sample((100,1)))
dataset = tf.data.Dataset.from_tensor_slices((features,labels))
sess = tf.Session()
def functionDummy(*x):
    total = 0
    print(x)
    for i in x:
        total = pow(i,2)
    return {"people":x,"survive":-total}

dataset = dataset.map(functionDummy)
#maxi = tf.math.argmax(dataset)
#print(maxi)
iterator = dataset.make_one_shot_iterator()
next_element = iterator.get_next()

item =  next_element
while True:
    try: 
        compare= tf.less(item["survive"],sess.run(next_element)["survive"])
        if sess.run(compare):
            item =sess.run(next_element)
    except tf.errors.OutOfRangeError:
        break

def fixFunction(*x):
    newpeople = item["people"] + x["people"] / 2
    return {"people":newpeople,"survive":functionDummy(newpeople)}
    
#dataset = dataset.map(fixFunction)

(<tf.Tensor 'arg0:0' shape=(1,) dtype=float64>, <tf.Tensor 'arg1:0' shape=(1,) dtype=float64>)


In [76]:
dicc = dict()

In [77]:
dicc["amarillo"] = 1

In [79]:
dicc["amarillo"] = 3
print(dicc)

{'amarillo': 3}


In [88]:
- pow(0.1205712,2) + pow(0.04627164,2)

-0.0123963496011504

In [91]:
pow(0.53631437,2) +  pow(0.14657798,2)

0.30911820768937737

In [99]:
functionDummy(0.6784184, 0.14471732)

(0.6784184, 0.14471732)


{'people': (0.6784184, 0.14471732), 'survive': -0.020943102707982404}

In [94]:
x = tf.Variable(-0.5, np.float32)
y = tf.Variable(+3.5, np.float32)

f = tf.add(tf.multiply(tf.constant(100.),
                       tf.pow(tf.subtract(tf.pow(x, 2), y), 2)),
           tf.pow(tf.subtract(tf.constant(1.0), x), 2))
#with tf.name_scope("inner"):
#    c_3 = tf.Variable(+3.0, np.float32,name="c") 

In [7]:
type(f)

tensorflow.python.framework.ops.Tensor

In [96]:
init_op = tf.initialize_all_variables()

# Later, when launching the model
with tf.Session() as sess:
    for a in tf.global_variables():
        sess.run(init_op)
        print(a)
        print(sess.run(a))
        #sess.run(a.assign(tf.random.uniform(a.shape)))
        print(sess.run(f))
        sess.run(f)      


ValueError: name: "Variable/Assign"
op: "Assign"
input: "Variable"
input: "arg0"
attr {
  key: "T"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "_class"
  value {
    list {
      s: "loc:@Variable"
    }
  }
}
attr {
  key: "use_locking"
  value {
    b: true
  }
}
attr {
  key: "validate_shape"
  value {
    b: true
  }
}
 must be from the same graph as name: "Variable/Assign"
op: "Assign"
input: "Variable"
input: "Variable/initial_value"
attr {
  key: "T"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "_class"
  value {
    list {
      s: "loc:@Variable"
    }
  }
}
attr {
  key: "use_locking"
  value {
    b: true
  }
}
attr {
  key: "validate_shape"
  value {
    b: true
  }
}
.

In [15]:
rows = []
for variable in tf.global_variables():
    col = []
    for i in range(30):
        col.append( tf.random.uniform(variable.shape))
    rows.append(col)
data = tf.data.Dataset.from_tensor_slices(tuple(rows))

iterator = data.make_initializable_iterator()
sess.run(iterator.initializer)
next_element = iterator.get_next()

item =  next_element
while True:
    try: 
        item =sess.run(next_element)
        print(item)
    except tf.errors.OutOfRangeError:
        break

(array([0.9598913 , 0.20910347], dtype=float32), array([0.89001286, 0.04134977], dtype=float32), 0.32677412)
(array([0.52631974, 0.21560538], dtype=float32), array([0.23398626, 0.01448655], dtype=float32), 0.25021636)
(array([0.1703999, 0.3608843], dtype=float32), array([0.20207131, 0.33776486], dtype=float32), 0.2953087)
(array([0.2830752 , 0.71027195], dtype=float32), array([0.1392647, 0.9055178], dtype=float32), 0.4199214)
(array([0.5799773 , 0.05198836], dtype=float32), array([0.05908942, 0.62962973], dtype=float32), 0.82864654)
(array([0.26339388, 0.04343009], dtype=float32), array([0.930684 , 0.9531534], dtype=float32), 0.77687335)
(array([0.26082635, 0.76803744], dtype=float32), array([0.6231047, 0.3949387], dtype=float32), 0.5616933)
(array([0.6456679, 0.8073181], dtype=float32), array([0.61074054, 0.7981739 ], dtype=float32), 0.3929416)
(array([0.4886974, 0.9460094], dtype=float32), array([0.12580955, 0.1924789 ], dtype=float32), 0.42994225)
(array([0.41895318, 0.56090784], dt

In [86]:
optimizer = Optimizer()
print(optimizer.variables)
optimizer.setFunction(f)
print(optimizer.model)
optimizer.printData()
print("ejecucion")
optimizer.interation()
optimizer.printData()

[<tf.Variable 'Variable:0' shape=(2,) dtype=float32_ref>, <tf.Variable 'Variable_1:0' shape=(2,) dtype=float32_ref>]
Tensor("Add:0", shape=(2,), dtype=float32)
(array([0.22726154, 0.8753946 ], dtype=float32), array([0.13882446, 0.04824436], dtype=float32))
(array([0.557837  , 0.19970405], dtype=float32), array([0.49570692, 0.84551644], dtype=float32))
(array([0.41187   , 0.22553372], dtype=float32), array([0.24134159, 0.05039287], dtype=float32))
(array([0.7393826 , 0.58171046], dtype=float32), array([0.88244367, 0.7107141 ], dtype=float32))
(array([0.858709 , 0.7678491], dtype=float32), array([0.8733084 , 0.54960823], dtype=float32))
(array([0.7876544 , 0.90770113], dtype=float32), array([0.47265565, 0.27746868], dtype=float32))
(array([0.9498594 , 0.03771114], dtype=float32), array([0.43159437, 0.5721835 ], dtype=float32))
(array([0.28348374, 0.62420475], dtype=float32), array([0.6146383, 0.1825676], dtype=float32))
(array([0.84212434, 0.93431914], dtype=float32), array([0.14989698, 

TypeError: In op 'Assign', input types ([tf.float32, tf.float32]) are not compatible with expected types ([tf.float32_ref, tf.float32])