In [1]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np
import tensorflow as tf

In [ ]:
class Optimizer:
    def __init__():
        this.sess = tf.Session()
    
    def evaluationSurvival(function, poblation):
        def temporal(*x):
            return {"people":x,"survive":function(x)}
        return poblation.map(temporal)
    
    def evaluationTensor(function):
        
    def init_var():
        this.variables = tf.global_variables()

    def generateInitialPoblation():
        this.init_var()
        rows = []
        for variable in tf.global_variables():
            col = []
            for i in range(30):
                col.append( tf.random.uniform(variable.shape))
            rows.append(col)
        data = tf.data.Dataset.from_tensor_slices(tuple(rows))
    
    def interation(dataset):
        iterator = dataset.make_initializable_iterator()
        sess.run(iterator.initializer)
        next_element = iterator.get_next()
        item =  next_element
        while True:
            try: 
                compare= tf.less(item["survive"],sess.run(next_element)["survive"])
                if sess.run(compare):
                    item =sess.run(next_element)
            except tf.errors.OutOfRangeError:
            break
        return(item)
    
    def fixFunction(function):
        def temporal(*x):
            newpeople = item["people"] + x["people"] / 2 #put some function
            return {"people":newpeople,"survive":functionDummy(newpeople)}
        return poblation.map(temporal)

    

In [2]:
features, labels = (np.random.sample((100,1)), np.random.sample((100,1)))
dataset = tf.data.Dataset.from_tensor_slices((features,labels))
sess = tf.Session()
def functionDummy(*x):
    total = 0
    print(x)
    for i in x:
        total = pow(i,2)
    return {"people":x,"survive":-total}

dataset = dataset.map(functionDummy)
#maxi = tf.math.argmax(dataset)
#print(maxi)
iterator = dataset.make_one_shot_iterator()
next_element = iterator.get_next()

item =  next_element
while True:
    try: 
        compare= tf.less(item["survive"],sess.run(next_element)["survive"])
        if sess.run(compare):
            item =sess.run(next_element)
    except tf.errors.OutOfRangeError:
        break

def fixFunction(*x):
    newpeople = item["people"] + x["people"] / 2
    return {"people":newpeople,"survive":functionDummy(newpeople)}
    
#dataset = dataset.map(fixFunction)

(<tf.Tensor 'arg0:0' shape=(1,) dtype=float64>, <tf.Tensor 'arg1:0' shape=(1,) dtype=float64>)


In [76]:
dicc = dict()

In [77]:
dicc["amarillo"] = 1

In [79]:
dicc["amarillo"] = 3
print(dicc)

{'amarillo': 3}


In [88]:
- pow(0.1205712,2) + pow(0.04627164,2)

-0.0123963496011504

In [91]:
pow(0.53631437,2) +  pow(0.14657798,2)

0.30911820768937737

In [99]:
functionDummy(0.6784184, 0.14471732)

(0.6784184, 0.14471732)


{'people': (0.6784184, 0.14471732), 'survive': -0.020943102707982404}

In [4]:
x = tf.Variable([-0.5 , -0.2], np.float32)
y = tf.Variable([+3.5, +0.2], np.float32)

f = tf.add(tf.multiply(tf.constant(100.),
                       tf.pow(tf.subtract(tf.pow(x, 2), y), 2)),
           tf.pow(tf.subtract(tf.constant(1.0), x), 2))
with tf.name_scope("inner"):
    c_3 = tf.Variable(+3.0, np.float32,name="c") 

Instructions for updating:
Colocations handled automatically by placer.


In [5]:
tf.random.uniform(tf.global_variables()[1].shape)

<tf.Tensor 'random_uniform:0' shape=(2,) dtype=float32>

In [57]:
init_op = tf.initialize_all_variables()

# Later, when launching the model
with tf.Session() as sess:
    for a in tf.global_variables():
        sess.run(init_op)
        print(sess.run(f))
        sess.run(a.assign(1))
        print(sess.run(f))
        sess.run(f)      


1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
1061.5
628.0
1061.5
61.5
1061.5
1059.5


In [15]:
rows = []
for variable in tf.global_variables():
    col = []
    for i in range(30):
        col.append( tf.random.uniform(variable.shape))
    rows.append(col)
data = tf.data.Dataset.from_tensor_slices(tuple(rows))

iterator = data.make_initializable_iterator()
sess.run(iterator.initializer)
next_element = iterator.get_next()

item =  next_element
while True:
    try: 
        item =sess.run(next_element)
        print(item)
    except tf.errors.OutOfRangeError:
        break

(array([0.9598913 , 0.20910347], dtype=float32), array([0.89001286, 0.04134977], dtype=float32), 0.32677412)
(array([0.52631974, 0.21560538], dtype=float32), array([0.23398626, 0.01448655], dtype=float32), 0.25021636)
(array([0.1703999, 0.3608843], dtype=float32), array([0.20207131, 0.33776486], dtype=float32), 0.2953087)
(array([0.2830752 , 0.71027195], dtype=float32), array([0.1392647, 0.9055178], dtype=float32), 0.4199214)
(array([0.5799773 , 0.05198836], dtype=float32), array([0.05908942, 0.62962973], dtype=float32), 0.82864654)
(array([0.26339388, 0.04343009], dtype=float32), array([0.930684 , 0.9531534], dtype=float32), 0.77687335)
(array([0.26082635, 0.76803744], dtype=float32), array([0.6231047, 0.3949387], dtype=float32), 0.5616933)
(array([0.6456679, 0.8073181], dtype=float32), array([0.61074054, 0.7981739 ], dtype=float32), 0.3929416)
(array([0.4886974, 0.9460094], dtype=float32), array([0.12580955, 0.1924789 ], dtype=float32), 0.42994225)
(array([0.41895318, 0.56090784], dt